Upload part 2 of source.

diff --git a/usr/src/:mk b/usr/src/:mk
--- a/usr/src/:mk
+++ b/usr/src/:mk
@@ -1,24 +1,54 @@
-#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
-#	  All Rights Reserved 
+#	Copyright (c) 1984 AT&T
+#	  All Rights Reserved
 
 #	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
 #	The copyright notice above does not evidence any
 #	actual or intended publication of such source code.
 
-#ident	"@(#)mk::mk	1.10.2.1"
+#ident	"@(#)mk::mk	1.10"
 #
 #	Shell script for rebuilding the UNIX System
 #
 trap "exit 1" 1 2 3 15
 if [ "$ROOT" = "" ]
 then
-	PATH=/usr/ccs/bin:/sbin:/usr/sbin:/usr/bin:/etc ; export PATH
+	PATH=/bin:/etc:/usr/bin; export PATH
 fi
 
 UID_NAME=`id|sed 's/[()]/ /gp'|awk '{print $2}'`
 
-#	create target directories
-./:mktarget
+# Check for the existance of target directories
+test -d ${ROOT:-"/"} || mkdir -p $ROOT
+cat -s target.dirs	|	# print contents of the target directory list
+egrep -v "^$|^#"	|	# get rid of blank lines and comments
+while read TARGETDIR MODE OWNER GROUP
+do
+	if [ ! -d ${ROOT}/$TARGETDIR ]
+	then
+		mkdir ${ROOT}/$TARGETDIR
+		if [ ! -d ${ROOT}/$TARGETDIR ]
+		then
+			echo "$0: stop: make of directory ${ROOT}/$TARGETDIR failed"
+			exit 1
+		fi
+			
+	fi
+	if [ "$UID_NAME" = "root" ]
+	then
+		if [ ! -z "$MODE" -a "$MODE" != "-" ]
+		then
+			chmod $MODE ${ROOT}/$TARGETDIR
+		fi
+		if [ ! -z "$OWNER" -a "$OWNER" != "-" ]
+		then
+			chown $OWNER ${ROOT}/$TARGETDIR
+		fi
+		if [ ! -z "$GROUP" -a "$GROUP" != "-" ]
+		then
+			chgrp $GROUP ${ROOT}/$TARGETDIR
+		fi
+	fi
+done
 
 #	install /usr/include and /usr/include/sys header files
 ./:mkhead
@@ -48,4 +78,9 @@ then
 fi
 #	build the OS itself
 ./:mkuts
+#	build the compatibility package
+if [ -d ucbcmd -d -s ucbhead -d -s ucblib ]
+then
+	./:mkucb
+fi
 exit 0
diff --git a/usr/src/pkg/rpc/preremove b/usr/src/pkg/rpc/preremove
--- a/usr/src/pkg/rpc/preremove
+++ b/usr/src/pkg/rpc/preremove
@@ -1,28 +1,23 @@
-#ident	"@(#)pkg.rpc:preremove	1.4"
+#ident	"@(#)pkg.rpc:preremove	1.3"
 
 #-----Remove administrative files
 
+rm -rf /var/yp || exit 1
+rm -rf /etc/net || exit 1
 rm -f /etc/publickey || exit 1
 rm -f /etc/netid || exit 1
 
-#-----Remove drivers
-FAILURE=2		# exit code if anything goes wrong
-MASTER=/etc/master.d	# home of master.d files
 
-/etc/drvinstall -u -m $MASTER/ktli -v 1.0	|| exit $FAILURE
-/etc/drvinstall -u -m $MASTER/krpc -v 1.0	|| exit $FAILURE
-/etc/drvinstall -u -m $MASTER/ides -v 1.0	|| exit $FAILURE
+#-----Remove etc/system entries
 
-
-#-----Remove /etc/system entries
 ETCSYSTEM=/etc/system
-COMMENTOUT="*INCLUDE:IDES"
+IDES="INCLUDE:IDES"
 
 if [ -f $ETCSYSTEM ]; then
-	if grep "$COMMENTOUT" $ETCSYSTEM >/dev/null 2>&1
+	if grep "$IDES" $ETCSYSTEM >/dev/null 2>&1
 	then
 	ed $ETCSYSTEM <<-!  >/dev/null 2>&1
-		g/$COMMENTOUT/d
+		g/$IDES/d
 		w
 		q
 	!
@@ -32,5 +27,12 @@ else
 	echo "The entry will have to be deleted manually at a later time."
 fi
 
+#-----Remove drivers
+FAILURE=2		# exit code if anything goes wrong
+MASTER=/etc/master.d	# home of master.d files
+
+/etc/drvinstall -u -m $MASTER/ktli -v 1.0	|| exit $FAILURE
+/etc/drvinstall -u -m $MASTER/krpc -v 1.0	|| exit $FAILURE
+/etc/drvinstall -u -m $MASTER/ides -v 1.0	|| exit $FAILURE
 
 exit 10			# indicates that the system should be rebooted
